Adds Bandit HTTP server support
newrelic/elixir_agent pull request #442
Opened 2024-09-26 11:24 UTC by rodrigocaldeira

### Description
This PR aims to add Bandit HTTP server support to New Relic's Elixir agent.

### Suggested changes
- Inclusion of `@bandit_start`, `@bandit_stop`, and `@bandit_exception` Plug events in `plug.ex`, each of them corresponding to [Bandit's telemetry spans](https://hexdocs.pm/bandit/Bandit.Telemetry.html) emitted by Bandit.

### Motivation
Currently New Relic's Elixir agent supports [plug_cowboy](https://github.com/elixir-plug/plug_cowboy) adapter only, and by applying the suggested changes to this lib I was able to collect and send web transactions to New Relic normally.

### Related issues
- https://github.com/newrelic/elixir_agent/issues/415

### Questions
I didn't find any test directly related to `NewRelic.Telemetry.Plug` module, so I couldn't find a way to check if the suggested changes would break any feature. Also I didn't find any indicator on the debug logs that could tell me if something was wrong during my tests, so any advise on how to create a test to check this is more than welcome!

2024-10-03 14:59 UTC, tpitale submitted a review, later dismissed

2024-10-03 15:12 UTC, binaryseed requested changes

2024-10-04 12:10 UTC, rodrigocaldeira commented on lib/new_relic/telemetry/plug.ex
> +  defp get_system_time(%{monotonic_time: monotonic_time}), do: monotonic_time
You are right @binaryseed .

cowboy uses [`:erlang.system_time()`](https://github.com/beam-telemetry/cowboy_telemetry/blob/main/src/cowboy_telemetry_h.erl#L13), on the other hand Bandit uses [`System.monotonic_time()`](https://github.com/mtrudel/bandit/blob/main/lib/bandit/telemetry.ex#L224).

Any ideas on how to solve this?

2024-10-04 12:13 UTC, rodrigocaldeira commented
> @rodrigocaldeira Would you also be able to take a look at why tests are failing?

Missing `mix format` caused that.

2024-10-04 16:56 UTC, binaryseed commented on lib/new_relic/telemetry/plug.ex
> +  defp get_system_time(%{monotonic_time: monotonic_time}), do: monotonic_time
Looking back on things, I think `system_time` was probably not necessary to add as an attribute in the first place. The agent already ensures that a `start_time` is tracked.

It's unlikely that `system_time` is used, but in the spirit of backward compatibility, I'd suggest that we simply don't include it for Bandit.

You could probably just pass `meas` to `add_start_attrs` and only include `system_time` for cowboy

2024-10-04 16:59 UTC, binaryseed commented on lib/new_relic/telemetry/plug.ex
> +      do: DistributedTrace.start(:http, get_headers(meta, server))
We could avoid converting headers to a map twice by gathering the headers into a variable before this line and passing them along to this function and `maybe_report_queueing`

2024-10-04 17:10 UTC, binaryseed commented
Ideally we test this along with the other `examples`...

The simplest way would probably be to add an additional `Endpoint` to the `phx_example` application, start it on a different port and configure it to use the Bandit adapter. Then duplicate the `phx_example_test.exs` and point it at the second endpoint by changing it's `request` function

2024-10-09 19:37 UTC, binaryseed commented
I rebased, added tests, and fixed a few issues to this in: https://github.com/newrelic/elixir_agent/pull/445

2024-10-09 19:40 UTC, binaryseed commented
Closing in favor of https://github.com/newrelic/elixir_agent/pull/445 (which includes all of the commits from this PR)

2024-10-09 19:40 UTC, closed without merging